<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('programs', function (Blueprint $t) { $t->id(); $t->string('title'); $t->string('slug')->unique(); $t->string('short_description', 500); $t->text('description')->nullable(); $t->string('degree_type'); $t->string('duration')->nullable(); $t->text('eligibility')->nullable(); $t->string('image_path')->nullable(); $t->string('icon_path')->nullable(); $t->unsignedInteger('display_order')->default(0)->index(); $t->boolean('is_featured')->default(false)->index(); $t->boolean('is_active')->default(true)->index(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('enquiries', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('email')->nullable()->index(); $t->string('phone', 30)->index(); $t->string('subject')->nullable(); $t->text('message'); $t->string('source')->default('website'); $t->string('status')->default('new')->index(); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->text('admin_notes')->nullable(); $t->string('ip_hash', 64)->nullable(); $t->text('user_agent')->nullable(); $t->timestamp('contacted_at')->nullable(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('admission_applications', function (Blueprint $t) { $t->id(); $t->string('application_number')->unique(); $t->string('full_name'); $t->string('email')->index(); $t->string('phone', 30)->index(); $t->date('date_of_birth')->nullable(); $t->foreignId('program_id')->constrained()->restrictOnDelete(); $t->string('previous_qualification')->nullable(); $t->text('message')->nullable(); $t->string('status')->default('submitted')->index(); $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('reviewed_at')->nullable(); $t->text('admin_notes')->nullable(); $t->timestamps(); $t->softDeletes(); });
        foreach (['testimonials','gallery'] as $table) Schema::create($table, function (Blueprint $t) use ($table) { $t->id(); if ($table === 'testimonials') { $t->string('student_name'); $t->string('course_or_role')->nullable(); $t->text('quote'); $t->unsignedTinyInteger('rating')->nullable(); $t->boolean('is_featured')->default(false)->index(); } else { $t->string('title'); $t->text('description')->nullable(); $t->string('alt_text'); } $t->string('image_path')->nullable(); $t->unsignedInteger('display_order')->default(0)->index(); $t->boolean('is_active')->default(true)->index(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('site_settings', function (Blueprint $t) { $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->string('type')->default('text'); $t->boolean('is_public')->default(true)->index(); $t->timestamps(); });
        Schema::create('activity_logs', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('resource_type'); $t->unsignedBigInteger('resource_id')->nullable(); $t->string('description'); $t->json('metadata')->nullable(); $t->string('ip_address', 45)->nullable(); $t->timestamps(); $t->index(['resource_type','resource_id']); });
    }
    public function down(): void { Schema::dropIfExists('activity_logs'); Schema::dropIfExists('site_settings'); Schema::dropIfExists('gallery'); Schema::dropIfExists('testimonials'); Schema::dropIfExists('admission_applications'); Schema::dropIfExists('enquiries'); Schema::dropIfExists('programs'); }
};
